
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Official "BOT or NOT?" Contest Rules</title>
<link rel="stylesheet" type="text/css" href="reset.css" />
<link rel="stylesheet" type="text/css" href="style.css?v=1.5" />
<!--[if lt IE 8]>
<link rel="stylesheet" type="text/css" href="ie.css" />
<script src="DD_belatedPNG_0.0.8a.js"></script>
<script>
  DD_belatedPNG.fix('h1 a, .left img, .bot img, a.playBtn, .round, a.invite');
</script>
<![endif]-->
<style>
 html, body {
 	overflow-x:auto;
 	overflow-y:auto;
 }
</style>
</head>
<body>
	<div id="container">
    	<div id="top">
        </div>
        <h1><a href="#">svedka</a></h1>
        <div id="mainContent">
			<div class="content-rule">
				<p style="color: #e30169; font-size: 16px; font-weight: bold; padding-top: 30px;">SVEDKA "BOT OR NOT" GAME</p>
				<p style="margin-bottom:20px;margin-top:5px;padding: 0;">OFFICIAL RULES - NO PURCHASE NECESSARY. </p>
				<p><strong>ELIGIBILITY:</strong> The SVEDKA Bot or Not Game (“Game”) is open to legal residents of the United States and the District of Columbia (except CA) who are 21 years of age or older as of the date of entry.  Void in California and where prohibited by law. Officers, directors and employees of Spirits Marque One LLC (“Sponsor”), Constellation Wines U.S., Inc, their affiliates, subsidiaries, licensed alcoholic beverage retailers and wholesalers, and other alcoholic beverage licensees, advertising and production agencies, electronic media firm, Sweepstakes Consulting, LLC, and members of their immediate families and those living in the same household are not eligible to participate.  All federal, state, and local laws and regulations apply. </p>

				<p><strong>HOW TO ENTER:</strong> Enter the game on the Facebook Platform Bot or Not Application at www.facebook.com/svedka (“Game Site”) by clicking “Like” to play between 3:00 am on September 13, 2010 and 2:59 am on November 7, 2010 (“Game Period”). All times are Eastern Time or “ET”. Limit of one entry or game play per person or e-mail address per week beginning each Monday (September 13, 2010) at 3:00 am until the following Monday (September 19, 2010) at 2:59 am, and each week thereafter for a total of eight (8) weeks. Online entrants must be the authorized account holder of the e-mail account from which the entry is made. Entries generated by script, macro or other automated or mechanical means will be void. This Game is not sponsored, endorsed or administered by or associated with Facebook.</p>

			<p><strong>HOW TO PLAY:</strong> Players will be asked to select one of two identical doors on the Game Site to reveal a “Bot” or “Not” prize.  If a “Bot” prize is revealed, the winner will be awarded the Bot prize revealed, pending verification of eligibility per these Official Rules. If a “Not” prize is revealed, the winner will be awarded the Not prize revealed or delivered a Not prize message. Winners will automatically receive a bounceback message requesting contact information required in the process of certifying winners. Winners will be contacted via e-mail within three (3) days after play date and may be required to complete and return an Affidavit of Eligibility and Liability/Publicity Release (“Affidavit”) within ten (10) days of the date on the Affidavit or prize will be forfeited. Once verified, winners can expect to receive their prize within three (3) weeks. Any undeliverable prize notification or prize returned as undeliverable will be awarded to an alternate winner by re-seeding the prize at random during Game Period.  Unclaimed prizes will not be awarded. </p>

			<p><strong>HOW FRIENDS CAN WIN:</strong> If a certified Bot Grand Prize winner had been referred to play the SVEDKA Bot or Not Game via the application by a friend, then the friend will be awarded an identical prize, pending verification of friend’s eligibility via an Affidavit.  Affidavit must be completed and returned within ten (10) days of the date on the Affidavit or prize will be forfeited.</p>

			<p>PRIZES and approximate retail values (“ARV”) are below. </p>
			<p><img src="images/rule-table.gif" alt="rule-table" width="447" height="452" /></p>

			<p>Total maximum ARV of all prizes ($12,055.02) plus maximum matching friend Bot Grand Prizes ($8,063.68*) is $20,118.70. Prizes do not include alcoholic beverages. Any expenses not mentioned above are the winner’s responsibility. No substitution for prize, unless at Sponsor’s sole discretion. Prizes are not transferable or redeemable for cash. Taxes are the winner’s responsibility. Prize acceptance constitutes permission (except where prohibited) to use winner’s name, photographs, and likeness for advertising and publicity purposes without additional compensation. Odds of winning a prize depend on the number of prizes available divided by the number of eligible game plays. Limit of one prize per household per week as defined in the “How to Enter” section. Prize suppliers/manufacturers are not affiliated with the sponsorship, endorsement, administration or responsibility for this Game. No sponsorship, endorsement, approval or responsibility for this Game by prize suppliers/manufacturers is intended or implied.</p>

			<p><strong>GENERAL TERMS:</strong></p>
			<p><strong>RELEASE:</strong> By entering or playing this Game, participants agree to be bound by these Official Rules. Participants, by participating in this Game, hereby waive and release, and agree to hold harmless the Sponsor, its subsidiaries, affiliates, Facebook, advertising and promotion agencies, and all of their respective officers, directors, employees, representatives and agents, from and against, any and all rights, claims and causes of action whatsoever that they may have, or which may arise, against any of them for any liability for any matter, cause of thing whatsoever, including but not limited to any injury, loss, damage, whether direct, compensatory, incidental or consequential, to person, including death and property, arising in whole or in part, directly or indirectly, from their acceptance, possession, use or misuse of, or inability to use a prize in the Game, or their participation in the Game, or their participation in any Game or prize related activity.  Winner also further acknowledges that Sponsor, its affiliates, subsidiaries, employees, officers, directors, and promotion and advertising agencies have neither made, nor are in any manner responsible or liable for, any warranty, representation or guarantee, express or implied, in fact or in law relative to any prize for this Game including but not limited to quality, condition or fitness for a particular purpose. </p>
			<p><strong>GAME FUNCTION:</strong> Sponsor and its agents are not responsible for lost, late, misdirected, damaged, incomplete or illegible entries or Internet technical, hardware, software, telephone, or transmission failures of any kind, which may limit a person’s ability to enter or play the Game. Sponsor and its agents are not responsible for any injury or damage to entrants’ or any other person’s computer related to or resulting from entering or downloading any materials in the Game. If, for any reason, the Game is not capable of running as planned by reason of tampering, unauthorized intervention, fraud, technical failures, computer virus or any other causes which, in the sole opinion of the Sponsor, may corrupt or affect the administration, security, fairness, integrity or proper conduct of this Game, Sponsor reserves the right, at its sole discretion, to cancel, terminate, modify or suspend the Game, and select the winners for the Game, from the entries received prior to the action taken or in other such manner as deemed fair and appropriate by Sponsor. Sponsor reserves the right to disqualify any entrant found to be disrupting the operation of the Game or its web site. Liability for any irregular game play is limited to replacement with another game play before Game ends on November 7, 2010.  If through error, more winning game plays are distributed than stated in these Official Rules, the actual number of winners will be selected in a random drawing from among all verified winning claims received by November 7, 2010. No more than the stated number of prizes in these Official Rules will be awarded. </p>
		<p><strong>DISPUTES:</strong> All issues and questions concerning these Official Rules, or the rights and obligations of the entrant and Sponsor in connection with the Game, shall be governed by, and construed in accordance with, the laws of New York State, without giving effect to any choice of law or conflict of law rules (whether of New York State or any other jurisdiction), which would cause the application of the laws of any jurisdiction other than New York State. No transfer or assignment of entries is permitted.  Entries become the sole property of the Sponsor.</p>

		<p><strong>WINNERS LIST:</strong>	 For a list of winners, send a self-addressed stamped envelope by December 31, 2010 to: SVEDKA Bot or Not Winners List, PO Box 25309, Rochester, NY 14625-0309.</p>

		<p><strong>SPONSOR:</strong> Spirits Marque One LLC, 598 Madison Avenue, New York, NY 10022. iPad and iPhone 4 are copyrights of Apple, Inc. All trademarks are the property of their respective owners.  No one but SVEDKA Vodka is a  sponsor of this Game.</p>
			<p>&nbsp;</p>
			</div> <!-- .content-rule -->
        </div>
    </div>

</body>
</html>